//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLOCATEDALLOWANCES
    {
        public int AllowanceId { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
